spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  resources:
    static-locations: 'classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/test/,file:${web.upload-path}'
      # 提示:如果我们显式地把自定义文件夹 和 默认的四个文件夹都写出来，那么都会有效(此时，优先级 从左至右 依次降低)
  web:
    image-path: 'F:\ideaPeoject\hello-springboot\src\main\resources\static\images'